title: Genome Analysis Module
description: "A hands-on introduction to genome analysis for the diagnosis of rare genetic disorders"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-paginate
